[build]
  # Indica dónde están los archivos compilados de Angular
  command = "ng build --configuration=production"
  publish = "dist/mygamestracker/browser"
  # Directorio donde se encuentran las funciones de Netlify
  functions = ".netlify/functions"

[dev]
  # Puerto para la simulación local de funciones
  functionsPort = 9999

[[plugins]]
  package = "@netlify/plugin-angular"
